[package]
name = "brainfuck-rs"
version = "0.5.0"
edition = "2024"
authors = ["Mun_Hammer"]
description = "A brainfuck compiler & interpreter"
keywords = ["compiler", "interpreter", "CLI", "WIP"]
publish = false
license = "GPL-3.0-or-later"
readme = "README.md"

[dependencies]
bitcode = { version = "0.5", features = ["derive"] }
clap = { version = "4.5.56", features = ["derive"], optional = true }
console = { version = "0.16.2", optional = true }
directories = { version = "6.0.0", optional = true }
rustyline = { version = "17.0.2", optional = true }

[dev-dependencies]
rstest = "0.26.1"

[features]
default = ["cli"]
interpret = ["dep:console"]
repl = ["interpret", "dep:rustyline", "dep:directories"]
cli = ["dep:clap", "repl", "dep:directories"]

[lints.clippy]
cargo = {level = "warn", priority = -1}
pedantic = {level = "warn", priority = 0}
large_stack_arrays = {level = "allow", priority = 1}
too_many_lines = {level = "allow", priority = 1}
multiple_crate_versions = {level = "allow", priority = 1}

[lints.rust]
missing_docs = "warn"
